### PR TITLE
Add locking to workspace create

### PR DESCRIPTION
**Pull request by jharwig**
- [x] joeferner
- [ ] mwizeman joeybrk372 jharwig sfeng88

...so multiple workspaces can't be created with same name

Points of Regression: Workspace deletion, creation

CHANGELOG
Fixed: Bug that caused multiple cases with same name to be created when deleting all workspaces and multiple sessions connected

### CODE REVIEW

**Comment by jharwig** [comment]
Can either @joeferner or @kunklejr review this?

**Comment by joeferner** [comment]
@jharwig one thing, can you add a comment or more info in the commit message to explain why this code exists.

**Comment by jharwig** [comment]
@joeferner done

**Comment by sfeng88** [comment]
LGTM

**Pull request merged**
