### PR TITLE
Hide visibility field when resolving to existing

### PR DESCRIPTION
**Pull request by jharwig**
- [x] joeferner
- [x] mwizeman joeybrk372 jharwig sfeng88

We didn't modify the visibility before so don't even show it.

Points of Regression: Resolve terms

CHANGELOG
Fixed: Don't show visibility field when resolving to existing entities (from text) as it was ignored

### CODE REVIEW

**Comment by jharwig** [comment]
I don't think we should keep it around. To make it worth keeping around they have to create new, add a visibility, then go back and resolve to existing, then back to create new (possibly with a different title.) I just don't think it's useful or common, and not worth keeping the component mounted.

**Comment by joeybrk372** [comment]
Sorry, I should have elaborated more on my comment. It seems like if you edited the visibility it would update the component state with the value, then if you went back and chose to resolve as existing and resolved that it would (incorrectly) send the modified visibility. Maybe in `onElementSelected` we should also clear `this.state.visibility`?

**Comment by jharwig** [comment]
Oh, right. It does send it, but we never used it. But I can clear it too in case the route changes

**Comment by joeybrk372** [comment]
LGTM

**Pull request merged**
