### PR TITLE
Fix un-i18ned strings

### PR DESCRIPTION
**Pull request by jharwig**
- [x] joeferner
- [x] mwizeman joeybrk372 jharwig sfeng88

Try to find all non-internationalized strings and fix.

https://github.com/visallo/visallo/issues/729

Points of Regression: Dashboard, Saved Search, Product toolbar, Timeline

CHANGELOG
Fixed: Replaced some missing internationalized strings

### CODE REVIEW

**Comment by joeybrk372** [comment]
**noticed these instances of non-i18n strings**
Notifications Dashboard Card: empty state `No Notifications Found`
Saved Search Dashboard Card: `Configure Saved Search...`, results limit option `Default`, aggregation `Add`, `Cancel` actions
BaseSelect: creating new `Create {0}`
Activity Panel: empty `No Activity`
Create relationship popover: `Invert`
User Account: no authorizations `none`
Element Inspector Toolbar Open: `Previously Viewed`

**Comment by jharwig** [comment]
@joeybrk372 Fixed those (found a few others around them)

**Comment by sfeng88** [comment]
Found one instance of non-i18n string
Timeline: timeline.fit

**Comment by jharwig** [comment]
@sfeng88 done

**Comment by sfeng88** [comment]
LGTM

**Pull request merged**
