### PR TITLE
Add basic print support

### PR DESCRIPTION
**Pull request by jharwig**
- [x] joeferner
- [x] mwizeman joeybrk372 jharwig sfeng88

* Sets main stylesheet to print
* Adds new print.less
  * Only prints dashboard, product view, element inspector (side & fullscreen)
  * Stacks elements after one another

print

Points of Regression: Printing only

CHANGELOG
Added: Basic browser print support for dashboard, product display, and element inspector

### CODE REVIEW

**Comment by sfeng88** [comment]
**When printing, some of the data is lost.**

Screenshots of dashboard, full screen, and product from Visallo:
screen shot 2018-01-29 at 10 39 55 am
screen shot 2018-01-29 at 10 44 13 am
screen shot 2018-01-29 at 10 44 32 am

Data Missing in Chrome dashboard print:
- Half of the welcome to visallo card
- Entity count card
[visallo_dashboard_chrome.pdf](https://github.com/visallo/visallo/files/1674480/visallo_dashboard_chrome.pdf)

Data Missing in IE11 dashboard print:
- 5th element inspector
fullscreen_ie11

**Saved Search Table:**
Do we want to do any styling for the saved search table in this PR? It looks the same in all three browsers.
dashboard_ie11

Copies of all of the pdf prints for all three browsers:
[map_product_ff52.pdf](https://github.com/visallo/visallo/files/1674720/map_product_ff52.pdf)
[map_product_chrome.pdf](https://github.com/visallo/visallo/files/1674721/map_product_chrome.pdf)
[full_screen_chrome.pdf](https://github.com/visallo/visallo/files/1674722/full_screen_chrome.pdf)
[visallo_dashboard_chrome.pdf](https://github.com/visallo/visallo/files/1674723/visallo_dashboard_chrome.pdf)
[product_inspector_ff52.pdf](https://github.com/visallo/visallo/files/1674724/product_inspector_ff52.pdf)
[fullscreen_ff52.pdf](https://github.com/visallo/visallo/files/1674725/fullscreen_ff52.pdf)
[product_ff52.pdf](https://github.com/visallo/visallo/files/1674726/product_ff52.pdf)
[Visallo_dashboard_ff52.pdf](https://github.com/visallo/visallo/files/1674727/Visallo_dashboard_ff52.pdf)
[visallo_product_chrome.pdf](https://github.com/visallo/visallo/files/1674728/visallo_product_chrome.pdf)
[map_product_ie11.pdf](https://github.com/visallo/visallo/files/1674729/map_product_ie11.pdf)

**Comment by jharwig** [comment]
this is really about how much we want to do. We have to add custom styling to all those cases individually to fix them.

And some things just can't be done without using a different approach like custom export.

**Comment by sfeng88** [comment]
@jharwig how about we merge this PR and just move the issue back to the backlog as an enhancement?

**Comment by jharwig** [comment]
Sounds good to me

**Pull request merged**
